services:
  db:
    image: postgis/postgis:17-3.5
    # env_file: ../.env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 8080:8080
