services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 8080:8080
