// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/observations": {
            "get": {
                "description": "List observations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observation"
                ],
                "summary": "List observations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Result limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Result offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_observation.ListObservationsResponse"
                        }
                    }
                }
            }
        },
        "/observations/{id}": {
            "get": {
                "description": "Get the detail of an observation by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observation"
                ],
                "summary": "Get Observation Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the observation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_observation.Observation"
                        }
                    }
                }
            }
        },
        "/sites": {
            "get": {
                "description": "List sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "site"
                ],
                "summary": "List sites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Site"
                            }
                        }
                    }
                }
            }
        },
        "/sites/{code}": {
            "get": {
                "description": "Get the detail of a site by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "site"
                ],
                "summary": "Get Site Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Code of the site",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Site"
                        }
                    }
                }
            }
        },
        "/species": {
            "get": {
                "description": "list all species",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "species"
                ],
                "summary": "List species",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Species"
                            }
                        }
                    }
                }
            }
        },
        "/species/by-common-name/{name}": {
            "get": {
                "description": "Get species detail by common name. Case insensitive. Underscores will be replaced with spaces.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "species"
                ],
                "summary": "Get species detail by common name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of the species. Case insensitive.",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Species"
                        }
                    }
                }
            }
        },
        "/species/observed": {
            "get": {
                "description": "List species observed within a date range, optionally filtered by site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "species"
                ],
                "summary": "List observed species",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site code",
                        "name": "siteCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start timestamp (RFC3339 format)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End timestamp (RFC3339 format)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_species.ObservedSpeciesResponse"
                        }
                    }
                }
            }
        },
        "/species/{id}": {
            "get": {
                "description": "Get species detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "species"
                ],
                "summary": "Get species detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of the species",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Species"
                        }
                    }
                }
            }
        },
        "/stats/dashboard": {
            "get": {
                "description": "Dashboard stats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Dashboard stats",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search start from",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search end to",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_stats.DashboardStatsResponse"
                        }
                    }
                }
            }
        },
        "/stats/observations": {
            "get": {
                "description": "Observation overview",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Observation overview",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search start from",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search end to",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by site block",
                        "name": "block",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by site code",
                        "name": "siteCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by taxa",
                        "name": "taxa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by species common_name",
                        "name": "commonName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_stats.ObservationOverviewResponse"
                        }
                    }
                }
            }
        },
        "/stats/observations/blocks": {
            "get": {
                "description": "Observation stats group by blocks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Observation stats group by blocks",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search start from",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search end to",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by site block",
                        "name": "block",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by site code",
                        "name": "siteCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by taxa",
                        "name": "taxa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by species common name",
                        "name": "commonName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_stats.ObservationByBlocksResponse"
                        }
                    }
                }
            }
        },
        "/stats/observations/sites": {
            "get": {
                "description": "Observation stats group by sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Observation stats group by sites",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search start from",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search end to",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by site block",
                        "name": "block",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by site code",
                        "name": "siteCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by taxa",
                        "name": "taxa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by species common name",
                        "name": "commonName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_stats.ObservationBySitesResponse"
                        }
                    }
                }
            }
        },
        "/stats/observations/timeseries": {
            "get": {
                "description": "Observation time series",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Observation time series",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search start from",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Search end to",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by site block",
                        "name": "block",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by site code",
                        "name": "siteCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by taxa",
                        "name": "taxa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by species common name",
                        "name": "commonName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_stats.ObservationTimeSeriesResponse"
                        }
                    }
                }
            }
        },
        "/storage/upload": {
            "post": {
                "description": "Upload a file to object storage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/storage/{key}": {
            "get": {
                "description": "Get a file from object storage by key",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Get a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_biomonash_nillumbik_internal_db.ForestType": {
            "type": "string",
            "enum": [
                "dry",
                "wet"
            ],
            "x-enum-varnames": [
                "ForestTypeDry",
                "ForestTypeWet"
            ]
        },
        "github_com_biomonash_nillumbik_internal_db.Observation": {
            "type": "object",
            "properties": {
                "appearanceEnd": {
                    "type": "integer"
                },
                "appearanceStart": {
                    "type": "integer"
                },
                "confidence": {
                    "type": "number"
                },
                "file": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.ObservationMethod"
                },
                "narrative": {
                    "type": "string"
                },
                "siteId": {
                    "type": "integer"
                },
                "speciesId": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_biomonash_nillumbik_internal_db.ObservationMethod": {
            "type": "string",
            "enum": [
                "audio",
                "camera",
                "observed"
            ],
            "x-enum-varnames": [
                "ObservationMethodAudio",
                "ObservationMethodCamera",
                "ObservationMethodObserved"
            ]
        },
        "github_com_biomonash_nillumbik_internal_db.Site": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "forest": {
                    "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.ForestType"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tenure": {
                    "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.TenureType"
                }
            }
        },
        "github_com_biomonash_nillumbik_internal_db.Species": {
            "type": "object",
            "properties": {
                "commonName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "indicator": {
                    "type": "boolean"
                },
                "native": {
                    "type": "boolean"
                },
                "reportable": {
                    "type": "boolean"
                },
                "scientificName": {
                    "type": "string"
                },
                "taxa": {
                    "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Taxa"
                }
            }
        },
        "github_com_biomonash_nillumbik_internal_db.Taxa": {
            "type": "string",
            "enum": [
                "bird",
                "mammal",
                "reptile"
            ],
            "x-enum-varnames": [
                "TaxaBird",
                "TaxaMammal",
                "TaxaReptile"
            ]
        },
        "github_com_biomonash_nillumbik_internal_db.TenureType": {
            "type": "string",
            "enum": [
                "public",
                "private"
            ],
            "x-enum-varnames": [
                "TenureTypePublic",
                "TenureTypePrivate"
            ]
        },
        "internal_observation.ListObservationsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "observations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.Observation"
                    }
                }
            }
        },
        "internal_observation.Observation": {
            "type": "object",
            "properties": {
                "appearanceIime": {
                    "type": "object",
                    "properties": {
                        "end": {
                            "type": "integer"
                        },
                        "start": {
                            "type": "integer"
                        }
                    }
                },
                "confidence": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "indicator": {
                    "type": "boolean"
                },
                "method": {
                    "$ref": "#/definitions/github_com_biomonash_nillumbik_internal_db.ObservationMethod"
                },
                "narrative": {
                    "type": "string"
                },
                "reportable": {
                    "type": "boolean"
                },
                "siteId": {
                    "type": "integer"
                },
                "speciesId": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_species.ObservedSpecies": {
            "type": "object",
            "properties": {
                "common_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "observation_count": {
                    "type": "integer"
                },
                "scientific_name": {
                    "type": "string"
                }
            }
        },
        "internal_species.ObservedSpeciesResponse": {
            "type": "object",
            "properties": {
                "species": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_species.ObservedSpecies"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_stats.BlockResponse": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "integer"
                },
                "observationCount": {
                    "type": "integer"
                },
                "speciesCount": {
                    "type": "integer"
                }
            }
        },
        "internal_stats.DashboardStatsResponse": {
            "type": "object",
            "properties": {
                "nativeSpeciesCount": {
                    "type": "integer"
                },
                "observationCount": {
                    "type": "integer"
                },
                "sitesCount": {
                    "type": "integer"
                },
                "speciesCount": {
                    "type": "integer"
                }
            }
        },
        "internal_stats.ObservationByBlocksResponse": {
            "type": "object",
            "properties": {
                "blocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_stats.BlockResponse"
                    }
                }
            }
        },
        "internal_stats.ObservationBySitesResponse": {
            "type": "object",
            "properties": {
                "sites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_stats.SiteResponse"
                    }
                }
            }
        },
        "internal_stats.ObservationOverviewResponse": {
            "type": "object",
            "properties": {
                "countByTaxa": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "nativeSpeciesCount": {
                    "type": "integer"
                },
                "observationCount": {
                    "type": "integer"
                },
                "speciesCount": {
                    "type": "integer"
                }
            }
        },
        "internal_stats.ObservationTimeSeriesResponse": {
            "type": "object",
            "properties": {
                "series": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/internal_stats.TimeSeriesPoint"
                        }
                    }
                }
            }
        },
        "internal_stats.SiteResponse": {
            "type": "object",
            "properties": {
                "observationCount": {
                    "type": "integer"
                },
                "siteCode": {
                    "type": "string"
                },
                "speciesCount": {
                    "type": "integer"
                }
            }
        },
        "internal_stats.TimeSeriesPoint": {
            "type": "object",
            "properties": {
                "observationCount": {
                    "type": "integer"
                },
                "speciesCount": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Nillubim Shire API",
	Description:      "This is the backend API for Nillumbik Shire project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
