basePath: /api/
definitions:
  db.Species:
    properties:
      common_name:
        type: string
      id:
        type: integer
      native:
        type: boolean
      scientific_name:
        type: string
      taxa:
        $ref: '#/definitions/db.Taxa'
    type: object
  db.Taxa:
    enum:
    - bird
    - mammal
    - reptile
    type: string
    x-enum-varnames:
    - TaxaBird
    - TaxaMammal
    - TaxaReptile
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /species:
    get:
      consumes:
      - application/json
      description: list all species
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Species'
            type: array
      summary: List species
      tags:
      - species
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
