// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: species.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSpecies = `-- name: CountSpecies :one
SELECT COUNT(*) FROM species
`

func (q *Queries) CountSpecies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSpecies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpecies = `-- name: CreateSpecies :one
INSERT INTO species (scientific_name, common_name, native, taxa, indicator, reportable, images)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
`

type CreateSpeciesParams struct {
	ScientificName string   `json:"scientificName"`
	CommonName     string   `json:"commonName"`
	Native         bool     `json:"native"`
	Taxa           Taxa     `json:"taxa"`
	Indicator      bool     `json:"indicator"`
	Reportable     bool     `json:"reportable"`
	Images         []string `json:"images"`
}

func (q *Queries) CreateSpecies(ctx context.Context, arg CreateSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, createSpecies,
		arg.ScientificName,
		arg.CommonName,
		arg.Native,
		arg.Taxa,
		arg.Indicator,
		arg.Reportable,
		arg.Images,
	)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonName,
		&i.Native,
		&i.Taxa,
		&i.Indicator,
		&i.Reportable,
		&i.Images,
		&i.IucnStatus,
	)
	return i, err
}

const deleteSpecies = `-- name: DeleteSpecies :exec
DELETE FROM species
WHERE id = $1
`

func (q *Queries) DeleteSpecies(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSpecies, id)
	return err
}

const getSpecies = `-- name: GetSpecies :one
SELECT id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
FROM species
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSpecies(ctx context.Context, id int64) (Species, error) {
	row := q.db.QueryRow(ctx, getSpecies, id)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonName,
		&i.Native,
		&i.Taxa,
		&i.Indicator,
		&i.Reportable,
		&i.Images,
		&i.IucnStatus,
	)
	return i, err
}

const getSpeciesByCommonName = `-- name: GetSpeciesByCommonName :one
SELECT id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
FROM species
WHERE lower(common_name) = LOWER($1) LIMIT 1
`

func (q *Queries) GetSpeciesByCommonName(ctx context.Context, lower string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByCommonName, lower)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonName,
		&i.Native,
		&i.Taxa,
		&i.Indicator,
		&i.Reportable,
		&i.Images,
		&i.IucnStatus,
	)
	return i, err
}

const getSpeciesByScientificName = `-- name: GetSpeciesByScientificName :one
SELECT id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
FROM species
WHERE lower(scientific_name) = LOWER($1) LIMIT 1
`

func (q *Queries) GetSpeciesByScientificName(ctx context.Context, lower string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByScientificName, lower)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonName,
		&i.Native,
		&i.Taxa,
		&i.Indicator,
		&i.Reportable,
		&i.Images,
		&i.IucnStatus,
	)
	return i, err
}

const listObservedSpecies = `-- name: ListObservedSpecies :many
SELECT
  sp.id,
  sp.scientific_name,
  sp.common_name,
  sp.native,
  sp.taxa,
  sp.indicator,
  sp.reportable,
  sp.images,
  sp.iucn_status,
  observation_count
FROM species sp
JOIN
(
  SELECT
      species_id,
      COUNT(id) AS observation_count
  FROM observations_with_details
  WHERE
    ($1::timestamp IS NULL OR timestamp >= $1::timestamp)
    AND ($2::timestamp IS NULL OR timestamp <= $2::timestamp)
    AND (
        $3::text[] IS NULL
        OR site_code = ANY($3)
      )
    AND (
        $4::integer[] IS NULL
        OR block = ANY($4)
      )
    AND (
        $5::taxa IS NULL
        OR taxa = $5::taxa
      )
  GROUP BY species_id
) as observed
ON sp.id = species_id
ORDER BY observation_count DESC
`

type ListObservedSpeciesParams struct {
	From      pgtype.Timestamp `json:"from"`
	To        pgtype.Timestamp `json:"to"`
	SiteCodes []string         `json:"siteCodes"`
	Blocks    []int32          `json:"blocks"`
	Taxa      NullTaxa         `json:"taxa"`
}

type ListObservedSpeciesRow struct {
	ID               int64    `json:"id"`
	ScientificName   string   `json:"scientificName"`
	CommonName       string   `json:"commonName"`
	Native           bool     `json:"native"`
	Taxa             Taxa     `json:"taxa"`
	Indicator        bool     `json:"indicator"`
	Reportable       bool     `json:"reportable"`
	Images           []string `json:"images"`
	IucnStatus       *string  `json:"iucnStatus"`
	ObservationCount int64    `json:"observationCount"`
}

// ListObservedSpecies returns species observed within a time range.
// If site_code is NULL, results include all sites.
// Returns species details along with observation count.
func (q *Queries) ListObservedSpecies(ctx context.Context, arg ListObservedSpeciesParams) ([]ListObservedSpeciesRow, error) {
	rows, err := q.db.Query(ctx, listObservedSpecies,
		arg.From,
		arg.To,
		arg.SiteCodes,
		arg.Blocks,
		arg.Taxa,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservedSpeciesRow{}
	for rows.Next() {
		var i ListObservedSpeciesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScientificName,
			&i.CommonName,
			&i.Native,
			&i.Taxa,
			&i.Indicator,
			&i.Reportable,
			&i.Images,
			&i.IucnStatus,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecies = `-- name: ListSpecies :many
SELECT id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
FROM species
ORDER BY scientific_name
`

func (q *Queries) ListSpecies(ctx context.Context) ([]Species, error) {
	rows, err := q.db.Query(ctx, listSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Species{}
	for rows.Next() {
		var i Species
		if err := rows.Scan(
			&i.ID,
			&i.ScientificName,
			&i.CommonName,
			&i.Native,
			&i.Taxa,
			&i.Indicator,
			&i.Reportable,
			&i.Images,
			&i.IucnStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpecies = `-- name: SearchSpecies :many
SELECT id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
FROM species
WHERE scientific_name ILIKE $1 OR common_name ILIKE $1
ORDER BY scientific_name
`

func (q *Queries) SearchSpecies(ctx context.Context, scientificName string) ([]Species, error) {
	rows, err := q.db.Query(ctx, searchSpecies, scientificName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Species{}
	for rows.Next() {
		var i Species
		if err := rows.Scan(
			&i.ID,
			&i.ScientificName,
			&i.CommonName,
			&i.Native,
			&i.Taxa,
			&i.Indicator,
			&i.Reportable,
			&i.Images,
			&i.IucnStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecies = `-- name: UpdateSpecies :one
UPDATE species
SET scientific_name = $2, common_name = $3, native = $4,
    taxa = $5, indicator = $6, reportable = $7, images = $8
WHERE id = $1
RETURNING id, scientific_name, common_name, native, taxa, indicator, reportable, images, iucn_status
`

type UpdateSpeciesParams struct {
	ID             int64    `json:"id"`
	ScientificName string   `json:"scientificName"`
	CommonName     string   `json:"commonName"`
	Native         bool     `json:"native"`
	Taxa           Taxa     `json:"taxa"`
	Indicator      bool     `json:"indicator"`
	Reportable     bool     `json:"reportable"`
	Images         []string `json:"images"`
}

func (q *Queries) UpdateSpecies(ctx context.Context, arg UpdateSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, updateSpecies,
		arg.ID,
		arg.ScientificName,
		arg.CommonName,
		arg.Native,
		arg.Taxa,
		arg.Indicator,
		arg.Reportable,
		arg.Images,
	)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.ScientificName,
		&i.CommonName,
		&i.Native,
		&i.Taxa,
		&i.Indicator,
		&i.Reportable,
		&i.Images,
		&i.IucnStatus,
	)
	return i, err
}

const updateSpeciesIUCNStatus = `-- name: UpdateSpeciesIUCNStatus :exec
UPDATE species
SET iucn_status = $1
WHERE id = $2
`

type UpdateSpeciesIUCNStatusParams struct {
	IucnStatus *string `json:"iucnStatus"`
	ID         int64   `json:"id"`
}

func (q *Queries) UpdateSpeciesIUCNStatus(ctx context.Context, arg UpdateSpeciesIUCNStatusParams) error {
	_, err := q.db.Exec(ctx, updateSpeciesIUCNStatus, arg.IucnStatus, arg.ID)
	return err
}
